export const bestSeller = [
  {
    id: "1",
    title: "RUNFALCON 3.0 SHOES",
    price: 3500,
    description:
      "Lace up for a run through the park or a walk to the coffee shop in these versatile adidas running shoes. They feel good from the minute you step in, thanks to the cushy Cloudfoam midsole. The textile upper feels comfy and breathable, and the rubber outsole gives you plenty of grip for a confident stride.",
    sale: 10,
    category: "Running",
    promo: "Best Sellers",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/cef8297b1dab42c48ee8af54009308c7_9366/Runfalcon_3.0_Shoes_White_HP7559_01_standard.jpg",
  },
  {
    id: "2",
    title: "DURAMO SPEED SHOES",
    price: 4500,
    description:
      "A combination of a lightweight & breathable engineered mesh upper with a full length LIGHTSTRIKE midsole for faster movement and durable outsole was built for runners looking to learn the ropes and push themselves to the next level.",
    sale: 20,
    category: "Running",
    promo: "Best Sellers",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/c3b091590220444996721e0d2d75d82d_9366/Duramo_Speed_Shoes_Black_IE9682_01_standard.jpg",
  },
  {
    id: "3",
    title: "BYW SELECT SHOES",
    price: 8500,
    description:
      "Keep that pep in your step all game long. These adidas basketball shoes have Lightstrike cushioning that keeps you comfortable without weighing you down.",
    sale: 30,
    category: "Basketball",
    promo: "Best Sellers",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/d51fd81610df4ee7a1fdafc50113d7db_9366/BYW_Select_Shoes_Black_IE9306_01_standard.jpg",
  },
  {
    id: "4",
    title: "ADIZERO BOSTON 12 SHOES",
    price: 8000,
    description:
      "The Adizero Boston 12 Shoes are built for mid- to long-distance running. They bring a race-day feel to training with a propulsive feel that comes from the glass-fiber infused ENERGYRODS 2.0, which limit energy loss underfoot. They're fast, but that does not come at the cost of durability — the midsole layers ultra-light LIGHTSTRIKE PRO cushioning with a new version of durable LIGHTSTRIKE 2.0 EVA.",
    sale: 10,
    category: "Running",
    promo: "Best Sellers",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/d9be7869e7444cebbcb1907eaf593f8d_9366/Adizero_Boston_12_Shoes_White_HP9705_01_standard.jpg",
  },
  {
    id: "5",
    title: "SUPERNOVA 2 RUNNING SHOES",
    price: 5500,
    description:
      " They feel good from the moment you step in, with a breathable mesh upper and padding at the tongue and heel. A precisely balanced mix of Bounce and BOOST cushioning delivers both comfort and energy so you enjoy every step on the road towards your personal running goals.",
    sale: 20,
    category: "Running",
    promo: "Best Sellers",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/6606b627c5ea40188a1bae2a018843db_9366/Supernova_2_Running_Shoes_Black_GW9088_01_standard.jpg",
  },
  {
    id: "6",
    title: "ADIZERO SELECT SHOES",
    price: 7300,
    description:
      "Made for players who use speed as their main weapon, these adidas basketball shoes have a lightweight feel to let you move freely on the hardwood.",
    sale: 30,
    category: "Basketball",
    promo: "Best Sellers",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/ea9bb1d6f16f4484bdc9afc5010b753d_9366/Adizero_Select_Shoes_Black_IE9285_01_standard.jpg",
  },
  {
    id: "7",
    title: "TRAE UNLIMITED SHOES",
    price: 5500,
    description:
      "Trae Young marches to the beat of his own drum. His signature adidas basketball shoes feature a low cut and a Bounce midsole that responds to your every move. The classic 3-Stripes have a serrated, textured design that goes from toe to midfoot. The rubber outsole with lateral grip zones gives you traction as you change directions or make quick cuts to the basket.",
    sale: 10,
    category: "Basketball",
    promo: "Best Sellers",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/3a82a0fb118f404894baaf3f00f52d18_9366/Trae_Unlimited_Shoes_Black_HQ1020_01_standard.jpg",
  },
  {
    id: "8",
    title: "TRAE YOUNG 2.0 SHOES",
    price: 7000,
    description:
      "One of the coldest on the hardwood, Trae Young is absolutely fearless. He'll take any shot at any time, and when it's all on the line, look out, because Trae is about to steal the show. ",
    sale: 20,
    category: "Basketball",
    promo: "Best Sellers",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/749a15ebcb5143c585f5af3b00f816ba_9366/Trae_Young_2.0_Shoes_Black_HQ0986_01_standard.jpg",
  },
  {
    id: "9",
    title: "D.O.N. ISSUE 4 SHOES",
    price: 6500,
    description:
      "Determination over negativity. That's what D.O.N. stands for, and it's also the fuel behind the fire that is Donovan Mitchell's fast and fearless game.",
    sale: 30,
    category: "Basketball",
    promo: "Best Sellers",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/d0966fc1a5184cb4b463af2d000670f5_9366/D.O.N._Issue_4_Shoes_Turquoise_HR0718_01_standard.jpg",
  },
  {
    id: "10",
    title: "HARDEN VOLUME 7 SHOES",
    price: 9000,
    description:
      "From his lethal stepback to his love of luxury fashion, there's no doubt that James Harden has style. With his signature shoes from adidas Basketball, it all comes into play.",
    sale: 10,
    category: "Basketball",
    promo: "Best Sellers",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/1387f49d03f64d8191f6af8d01437ef4_9366/Harden_Volume_7_Shoes_White_HQ3425_01_standard.jpg",
  },
  {
    id: "11",
    title: "ULTRABOOST 1.0 SHOES",
    price: 9500,
    description:
      "From everyday errands to exploring the city, these adidas Ultraboost shoes bring undefeated comfort. The adidas PRIMEKNIT upper is designed to hug your feet for all-day support. ",
    sale: 10,
    category: "Running",
    promo: "Best Sellers",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/1512cb61cfed43f8bc32a148e3adca05_9366/Ultraboost_1.0_Shoes_Pink_ID9664_01_standard.jpg",
  },
  {
    id: "12",
    title: "SUPERNOVA 3 RUNNING SHOES",
    price: 6000,
    description:
      "Whether you run near, far, swift or slow, the adidas Supernova 3 shoes help you run in your comfort zone.",
    sale: 20,
    category: "Running",
    promo: "Best Sellers",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b0934465fe174f34b573ba45101e37cc_9366/Supernova_3_Running_Shoes_White_HQ1805_01_standard.jpg",
  },
  {
    id: "13",
    title: "RUN 60S 3.0 LIFESTYLE RUNNING SHOES",
    price: 3000,
    description:
      "Enjoy those long weekend walks in these adidas trainers. Taking design cues from archival running shoes, they have a clean, versatile aesthetic that stays grounded with an elevated midsole.",
    sale: 30,
    category: "Running",
    promo: "Best Sellers",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/9064bdb0c25b4a75b1ed771e53a49c54_9366/Run_60s_3.0_Lifestyle_Running_Shoes_White_ID1853_01_standard.jpg",
  },
  {
    id: "14",
    title: "CLOUDFOAM PURE SHOES",
    price: 3900,
    description:
      "No one gets it done like you do. Step into a pair of adidas shoes that can keep up. The swift, angular design embodies your on-the-go lifestyle. The Cloudfoam midsole brings ultimate cushioning, so every step feels light and springy. It's a versatile look, with that confident style you're known for.",
    sale: 10,
    category: "Running",
    promo: "Best Sellers",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b9024954fc7c4b7492664e133a9284cb_9366/Cloudfoam_Pure_Shoes_White_IG7376_01_standard.jpg",
  },
  {
    id: "15",
    title: "DURAMO RC SHOES",
    price: 3000,
    description:
      "Run a little faster. Run a little further. With the light, soft and supportive feel of these adidas running shoes, you're set to take the next step in your running journey. ",
    sale: 20,
    category: "Running",
    promo: "Best Sellers",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/c43b629673064f92830dafd3013e8c8e_9366/Duramo_RC_Shoes_Blue_ID2701_01_standard.jpg",
  },
  {
    id: "16",
    title: "DURAMO SPEED SHOES",
    price: 4500,
    description:
      "A combination of a lightweight & breathable engineered mesh upper with a full length LIGHTSTRIKE midsole for faster movement and durable outsole was built for runners looking to learn the ropes and push themselves to the next level.",
    sale: 30,
    category: "Running",
    promo: "Best Sellers",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/2d3755c881f849c0926538a1f54206c9_9366/Duramo_Speed_Shoes_Black_ID9854_01_standard.jpg",
  },
  {
    id: "17",
    title: "DROPSET TRAINER SHOES",
    price: 6500,
    description:
      "Tackle your strength training and gym workouts without hesitation. These adidas training shoes help you level up your game. ",
    sale: 30,
    category: "Training",
    promo: "Best Sellers",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/dc017a7102264fcdb8a7ae6f011e0cdd_9366/Dropset_Trainer_Shoes_Green_GW3900_01_standard.jpg",
  },
  {
    id: "18",
    title: "GAMECOURT 2.0 TENNIS SHOES",
    price: 3500,
    description:
      "Stay confident through every game, set and match. A lightweight mesh upper and padded heel make these adidas Gamecourt 2.0 shoes your perfect tennis partner.",
    sale: 10,
    category: "Tennis",
    promo: "Best Sellers",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b4404527c842424a84b3ae970092eb5e_9366/Gamecourt_2.0_Tennis_Shoes_Turquoise_GW6262_01_standard.jpg",
  },
  {
    id: "19",
    title: "ADIZERO UBERSONIC 4 TENNIS SHOES",
    price: 6800,
    description:
      "Speed buys time. Time earns points. That's why these adidas Adizero Ubersonic 4 tennis shoes were designed to get you to the ball faster.",
    sale: 20,
    category: "Tennis",
    promo: "Best Sellers",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/fe46bc927de24f948bd8af4701505e82_9366/Adizero_Ubersonic_4_Tennis_Shoes_Orange_HQ8392_01_standard.jpg",
  },
  {
    id: "20",
    title: "BARRICADE TENNIS SHOES",
    price: 4900,
    description:
      "The perfect platform for hard court domination. These adidas Barricade tennis shoes have an intuitive lacing system that locks you in by pulling down the neoprene tongue to match your foot shape.",
    sale: 30,
    category: "Tennis",
    promo: "Best Sellers",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/7778b41b65f746dcae6dae9700cb08ce_9366/Barricade_Tennis_Shoes_Orange_GW3816_01_standard.jpg",
  },

  {
    id: "31",
    title: "Fresh Foam X 1080v12",
    price: 7999,
    description:
      "The 1080 delivers top-of-the-line performance to every kind of runner, whether you’re training for world-class competition, or catching a rush hour train. The Fresh Foam X 1080v12 represents a consistent progression of the model’s signature qualities.",
    sale: 10,
    category: "Running",
    promo: "Best Sellers",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://nb.scene7.com/is/image/NB/m108012v_nb_02_i?$pdpflexf2$&qlt=80&fmt=webp&wid=440&hei=440",
  },
  {
    id: "32",
    title: "1540v3",
    price: 8999,
    description:
      "Our 1540v3 is kitted out with technology that helps deliver mile-after-mile stability and combat overpronation. It's made with two layers of performance foam that offers superior support and a soft rebound.",
    sale: 20,
    category: "Running",
    promo: "Best Sellers",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://nb.scene7.com/is/image/NB/m1540mb3_nb_02_i?$pdpflexf2$&qlt=80&fmt=webp&wid=440&hei=440",
  },
  {
    id: "33",
    title: "Fresh Foam X 1080 Unlaced",
    price: 3999,
    description:
      "What makes the 1080 unique isn’t just that it’s the best running shoe we make. It delivers the top-of-the-line performance of the best running shoe we make to every kind of runner.",
    sale: 30,
    category: "Running",
    promo: "Best Sellers",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://nb.scene7.com/is/image/NB/m1080scb_nb_02_i?$pdpflexf2$&qlt=80&fmt=webp&wid=440&hei=440",
  },
  {
    id: "34",
    title: "Fresh Foam X Hierro v7",
    price: 6999,
    description:
      "Uneven terrain, debris, and moisture are unique challenges to footwear that require specialized construction. For those who take going off the beaten path literally, there’s the Fresh Foam X Hierro, a dedicated, off-road application of our best running technology.",
    sale: 10,
    category: "Running",
    promo: "Best Sellers",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://nb.scene7.com/is/image/NB/mthieri7_nb_02_i?$pdpflexf2$&qlt=80&fmt=webp&wid=440&hei=440",
  },
  {
    id: "35",
    title: "Fresh Foam Arishi v4 GTX",
    price: 2999,
    description:
      "Hit the road in any weather with the New Balance Fresh Foam Arishi v4 GTX running shoe. Designed to be capable, comfortable and durable, this runner features Fresh Foam midsole cushioning for a plush underfoot feel, and GORE-TEX® waterproof fabric in the upper to help keep feet protected.",
    sale: 20,
    category: "Running",
    promo: "Best Sellers",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://nb.scene7.com/is/image/NB/marisgb4_nb_02_i?$pdpflexf2$&qlt=80&fmt=webp&wid=440&hei=440",
  },
  {
    id: "36",
    title: "Minimus TR",
    price: 5599,
    description:
      "Whether you enjoy lifting weights or performing weekly HIIT workouts, our Minimus TR men's training shoe is a must-have for anyone who craves support and a lightweight feel.",
    sale: 30,
    category: "Training",
    promo: "Best Sellers",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://nb.scene7.com/is/image/NB/mxmtrlk1_nb_02_i?$pdpflexf2$&qlt=80&fmt=webp&wid=440&hei=440",
  },
];
