export const newArrivals = [
  {
    id: "64",
    title: "Nike SuperRep Go 3 Flyknit Next Nature",
    price: 5295,
    description:
      "The new Nike SuperRep Go 3 Flyknit is a radical design story rooted in innovation. Made from at least 20% recycled content by weight, the zoned Flyknit construction wraps your foot in 360 degrees of comfort and support.",
    sale: 30,
    category: "Training",
    promo: "New Arrivals",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/00cd41dc-cff3-4cf5-a47c-37fb3ae02698/superrep-go-3-flyknit-next-nature-training-shoes-zKqgRc.png",
  },
  {
    id: "65",
    title: "Nike City Rep TR",
    price: 2895,
    description:
      "The Nike City Rep TR is a versatile shoe that brings durability and flexibility to your active lifestyle.",
    sale: 30,
    category: "Training",
    promo: "New Arrivals",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/8e714e1e-ecc0-430c-9a57-0ef48d1710a9/city-rep-tr-training-shoes-k6VCMk.png",
  },
  {
    id: "66",
    title: "Nike Zoom Bella 6",
    price: 4695,
    description:
      "Unleash your innermost strength and spirit in the Nike Zoom Bella 6. This design supports heavy lifts, explosive movements and primal post-set struts as you flaunt your hard-earned progress on the gym floor.",
    sale: 10,
    category: "Training",
    promo: "New Arrivals",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/d638751c-f0df-49bc-ba7f-3a8229fc3416/zoom-bella-6-training-shoes-PX75xS.png",
  },
  {
    id: "67",
    title: "Nike Free Metcon 4",
    price: 3869,
    description:
      "The Nike Free Metcon 4 combines flexibility with stability to help you get the most out of your training programme. ",
    sale: 10,
    category: "Training",
    promo: "New Arrivals",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/d8b946dc-2f54-4c8c-bb79-36cdbcad876c/free-metcon-4-training-shoes-k5B8Jf.png",
  },
  {
    id: "68",
    title: "Air Jordan XXXVII Low",
    price: 10839,
    description:
      "A basketball shoe for you and your unique game. We gathered insights from female ballers and integrated them into this edition of the AJ XXXVII Low, engineered specifically for women.",
    sale: 20,
    category: "Basketball",
    promo: "New Arrivals",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/421da929-53d5-44fe-a658-6635acec612a/air-jordan-xxxvii-low-basketball-shoes-Z2glMj.png",
  },
  {
    id: "69",
    title: "Air Jordan 1 Elevate High",
    price: 8595,
    description:
      "Classic Jordan style reaches new heights in this lifted AJ-1. The platform stance and high-top collar make a statement, while crisp leather and flashy finishes make these kicks the winning assist your outfit needs.",
    sale: 30,
    category: "Basketball",
    promo: "New Arrivals",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/bac26860-b8ac-4dfa-92c0-00ebc8416e2b/air-jordan-1-elevate-high-shoes-rKPNHR.png",
  },
  {
    id: "70",
    title: "Air Jordan 1 Mid SE",
    price: 4439,
    description:
      "These AJ1s give a classic silhouette the royal treatment. An all-over velvet upper in Purple Smoke looks super luxe, while the embroidered Swoosh, plush laces and colour-matched outsole let you hit refresh on a beloved hoops design.",
    sale: 10,
    category: "Basketball",
    promo: "New Arrivals",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/ac05bee4-331c-43b0-bf9d-8396f3ba4983/air-jordan-1-mid-se-shoes-56JJcP.png",
  },
  {
    id: "71",
    title: "Men's UA HOVR™ Phantom 3 Storm",
    price: 5157,
    description:
      "The off-season is for getting better. That means lots of running. Fast, stretchy UA HOVR™ Phantom 3 helps you explode through interval after interval with even more energy-returning UA HOVR™ cushioning. Run now…win later.",
    sale: 10,
    category: "Running",
    promo: "New Arrivals",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://underarmour.scene7.com/is/image/Underarmour/3025522-001_DEFAULT?rp=standard-30pad|pdpMainDesktop&scl=1&fmt=jpg&qlt=85&resMode=sharp2&cache=on,on&bgc=f0f0f0&wid=566&hei=708&size=536,688",
  },
  {
    id: "72",
    title: "Men's UA Flow Velociti Wind 2",
    price: 5397,
    description:
      "There's fast, and then there's UA Flow fast. Lightweight, rubberless, and durable, our newest cushioning gives a close-to-the-ground, grippy feeling of speed. The kind of speed that feels like you've got the wind at your back.",
    sale: 20,
    category: "Running",
    promo: "New Arrivals",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://underarmour.scene7.com/is/image/Underarmour/3024903-001_DEFAULT?rp=standard-30pad|pdpMainDesktop&scl=1&fmt=jpg&qlt=85&resMode=sharp2&cache=on,on&bgc=f0f0f0&wid=566&hei=708&size=536,688",
  },
  {
    id: "73",
    title: "Men's UA Charged Assert 10",
    price: 3595,
    description:
      "These are running shoes anyone can wear to go faster—with Charged Cushioning® to help protect against impact, a breathable upper, and durability for miles.",
    sale: 30,
    category: "Running",
    promo: "New Arrivals",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://underarmour.scene7.com/is/image/Underarmour/3026175-003_DEFAULT?rp=standard-30pad|pdpMainDesktop&scl=1&fmt=jpg&qlt=85&resMode=sharp2&cache=on,on&bgc=f0f0f0&wid=566&hei=708&size=536,688",
  },
  {
    id: "74",
    title: "Men's UA HOVR™ Machina 3 Storm",
    price: 6446,
    description:
      "Best for: Long & everyday runs in the rain with a water-repellent upper & reflective details, UA Storm technology treated upper repels water without sacrificing breathability, Aerodynamic heel design for support without any excess layers or bulk",
    sale: 10,
    category: "Running",
    promo: "New Arrivals",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://underarmour.scene7.com/is/image/Underarmour/3025798-003_DEFAULT?rp=standard-30pad|pdpMainDesktop&scl=1&fmt=jpg&qlt=85&resMode=sharp2&cache=on,on&bgc=f0f0f0&wid=566&hei=708&size=536,688",
  },
  {
    id: "75",
    title: "Men's Project Rock BSR 3 ",
    price: 6995,
    description:
      "These shoes were built for explosive movement and dynamic training, day in and day out. You never let up, neither do these—stability for strength training, flexibility for HIIT, and cushioning for mobility.",
    sale: 20,
    category: "Training",
    promo: "New Arrivals",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://underarmour.scene7.com/is/image/Underarmour/3026462-102_DEFAULT?rp=standard-30pad|pdpMainDesktop&scl=1&fmt=jpg&qlt=85&resMode=sharp2&cache=on,on&bgc=f0f0f0&wid=566&hei=708&size=536,688",
  },
  {
    id: "76",
    title: "Men's UA HOVR™ Rise 4 ",
    price: 5595,
    description:
      "Our amazing energy-returning UA HOVR™ cushioning meets the flexible stability of our UA Tribase™outsole. That means every burpee, every ladder drill, every box jump, every movement becomes more explosive.",
    sale: 30,
    category: "Training",
    promo: "New Arrivals",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://underarmour.scene7.com/is/image/Underarmour/3025565-001_DEFAULT?rp=standard-30pad|pdpMainDesktop&scl=1&fmt=jpg&qlt=85&resMode=sharp2&cache=on,on&bgc=f0f0f0&wid=566&hei=708&size=536,688",
  },
  {
    id: "77",
    title: "Men's UA TriBase™ Reign 4 Pro Amp",
    price: 4977,
    description:
      "The better your contact with the floor during your workouts, the better those workouts are going to be. The low, stable triangular base of the UA TriBase™ tech will help you through every rep, set, and WOD.",
    sale: 10,
    category: "Training",
    promo: "New Arrivals",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://underarmour.scene7.com/is/image/Underarmour/3025979-500_DEFAULT?rp=standard-30pad|pdpMainDesktop&scl=1&fmt=jpg&qlt=85&resMode=sharp2&cache=on,on&bgc=f0f0f0&wid=566&hei=708&size=536,688",
  },
  {
    id: "78",
    title: " UA Reign Lifter",
    price: 11129,
    description:
      "If you're a serious lifter these are the shoes you need. The midfoot strap keeps you locked in, the TPU heel lift helps support hip and ankle flexibility, and the outsole is firm and flat for maximum ground contact.",
    sale: 30,
    category: "Training",
    promo: "New Arrivals",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://underarmour.scene7.com/is/image/Underarmour/3023735-001_DEFAULT?rp=standard-30pad|pdpMainDesktop&scl=1&fmt=jpg&qlt=85&resMode=sharp2&cache=on,on&bgc=f0f0f0&wid=566&hei=708&size=536,688",
  },
  {
    id: "79",
    title: "UA Lockdown 6",
    price: 4295,
    description:
      "These are light, comfortable, and tough enough to last all season—making them a go-to court shoe year after year.",
    sale: 10,
    category: "Basketball",
    promo: "New Arrivals",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://underarmour.scene7.com/is/image/Underarmour/3025616-600_DEFAULT?rp=standard-30pad|pdpMainDesktop&scl=1&fmt=jpg&qlt=85&resMode=sharp2&cache=on,on&bgc=f0f0f0&wid=566&hei=708&size=536,688",
  },
  {
    id: "80",
    title: "Curry 2",
    price: 3451,
    description:
      "Own the court in the original Curry 2s—back for a special, limited re-release. Make every cut more powerful with shock-absorbing cushioning and the custom-fit of a foot-hugging UA Speedform upper.",
    sale: 20,
    category: "Basketball",
    promo: "New Arrivals",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://underarmour.scene7.com/is/image/Underarmour/3026052-600_DEFAULT?rp=standard-30pad|pdpMainDesktop&scl=1&fmt=jpg&qlt=85&resMode=sharp2&cache=on,on&bgc=f0f0f0&wid=566&hei=708&size=536,688",
  },
  {
    id: "81",
    title: "UA Charged Bandit Trail 2",
    price: 3357,
    description:
      "Specially built for trail running, with crazy cushioning, traction that grips even muddy terrain, and the extra protection trail runners need to keep going.",
    sale: 10,
    category: "Running",
    promo: "New Arrivals",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://underarmour.scene7.com/is/image/Underarmour/3024191-500_DEFAULT?rp=standard-30pad|pdpZoomDesktop&scl=0.50&fmt=jpg&qlt=85&resMode=sharp2&cache=on,on&bgc=f0f0f0&wid=1836&hei=1950&size=850,850",
  },
  {
    id: "82",
    title: "UA HOVR™ Sonic 5",
    price: 4197,
    description:
      "The UA HOVR™ Sonic is a no-brainer for runners who like distance but want more flexibility, a breathable feel, and the real-time feedback of Form Coaching from UA MapMyRun™ to help you run better every time you lace them up.",
    sale: 20,
    category: "Running",
    promo: "New Arrivals",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://underarmour.scene7.com/is/image/Underarmour/3024906-001_DEFAULT?rp=standard-30pad|pdpMainDesktop&scl=1&fmt=jpg&qlt=85&resMode=sharp2&cache=on,on&bgc=f0f0f0&wid=566&hei=708&size=536,688",
  },
  {
    id: "83",
    title: "UA HOVR™ Phantom 3",
    price: 5397,
    description:
      "The off-season is for getting better. That means lots of running. Fast, stretchy UA HOVR™ Phantom 3 helps you explode through interval after interval with even more energy-returning UA HOVR™ cushioning. Run now…win later.",
    sale: 30,
    category: "Running",
    promo: "New Arrivals",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://underarmour.scene7.com/is/image/Underarmour/3025517-602_DEFAULT?rp=standard-30pad|pdpZoomDesktop&scl=0.50&fmt=jpg&qlt=85&resMode=sharp2&cache=on,on&bgc=f0f0f0&wid=1836&hei=1950&size=850,850",
  },
  {
    id: "84",
    title: " UA HOVR™ Phantom 3 Slip Pride ",
    price: 8595,
    description:
      "This year's UA Pride collection supports Unmatched Athlete, WorldPride, and Rainbow Labs, each with the goal of providing safe places for LGBTQ+ athletes and allies to play and compete.",
    sale: 10,
    category: "Running",
    promo: "New Arrivals",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://underarmour.scene7.com/is/image/Underarmour/3026350-100_DEFAULT?rp=standard-30pad|pdpMainDesktop&scl=1&fmt=jpg&qlt=85&resMode=sharp2&cache=on,on&bgc=f0f0f0&wid=566&hei=708&size=536,688",
  },
  {
    id: "85",
    title: "UA Charged Intake 5",
    price: 3357,
    description:
      "UA Charged Intake was designed to keep your feet cooler and drier, so you can log as many miles as you want.",
    sale: 10,
    category: "Running",
    promo: "New Arrivals",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://underarmour.scene7.com/is/image/Underarmour/3023564-600_DEFAULT?rp=standard-30pad|pdpMainDesktop&scl=1&fmt=jpg&qlt=85&resMode=sharp2&cache=on,on&bgc=f0f0f0&wid=566&hei=708&size=536,688",
  },
  {
    id: "86",
    title: "UA HOVR™ Omnia Metallic",
    price: 3777,
    description:
      "Feels like a cloud and fits like a glove. We took our super-springy UA HOVR™ cushioning and put it in a trainer that's built specifically for the female foot.",
    sale: 10,
    category: "Training",
    promo: "New Arrivals",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://underarmour.scene7.com/is/image/Underarmour/3025567-001_DEFAULT?rp=standard-30pad|pdpMainDesktop&scl=1&fmt=jpg&qlt=85&resMode=sharp2&cache=on,on&bgc=f0f0f0&wid=566&hei=708&size=536,688",
  },
  {
    id: "87",
    title: " UA SlipSpeed™ ",
    price: 8595,
    description:
      "These are the most versatile training shoes we've ever made. They feel great, feel cool, cushion better, fit perfectly, handle your toughest training, AND have a heel that converts easily from recover mode to train mode.",
    sale: 30,
    category: "Training",
    promo: "New Arrivals",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://underarmour.scene7.com/is/image/Underarmour/3027057-300_DEFAULT?rp=standard-30pad|pdpMainDesktop&scl=1&fmt=jpg&qlt=85&resMode=sharp2&cache=on,on&bgc=f0f0f0&wid=566&hei=708&size=536,688",
  },
  {
    id: "88",
    title: "UA TriBase™ Reign 4 ",
    price: 8595,
    description:
      "If you're a serious lifter these are the shoes you need. The midfoot strap keeps you locked in, the TPU heel lift helps support hip and ankle flexibility, and the outsole is firm and flat for maximum ground contact.",
    sale: 30,
    category: "Training",
    promo: "New Arrivals",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://underarmour.scene7.com/is/image/Underarmour/3025053-500_DEFAULT?rp=standard-30pad|pdpZoomDesktop&scl=0.50&fmt=jpg&qlt=85&resMode=sharp2&cache=on,on&bgc=f0f0f0&wid=1836&hei=1950&size=850,850",
  },
  {
    id: "89",
    title: "UA Flow Breakthru 3 LE",
    price: 6795,
    description:
      "Women's feet are a different shape than men's. That's a fact. These shoes were built for women by women, giving you the best fit, support, and flex. And, with UA Flow cushioning you also get the best grip on any court.",
    sale: 10,
    category: "Basketball",
    promo: "New Arrivals",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://underarmour.scene7.com/is/image/Underarmour/3026761-100_DEFAULT?rp=standard-30pad|pdpMainDesktop&scl=1&fmt=jpg&qlt=85&resMode=sharp2&cache=on,on&bgc=f0f0f0&wid=566&hei=708&size=536,688",
  },
  {
    id: "90",
    title: "Curry 1 Low FloTro",
    price: 3456,
    description:
      "These shoes combine the light, grippy speed of Curry 10's UA Flow cushioning with the custom feel of your favorite Curry 1's form-fitting upper. Why? Because this unreal combo puts you a step ahead all game long.",
    sale: 20,
    category: "Basketball",
    promo: "New Arrivals",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://underarmour.scene7.com/is/image/Underarmour/3026278-401_DEFAULT?rp=standard-30pad|pdpMainDesktop&scl=1&fmt=jpg&qlt=85&resMode=sharp2&cache=on,on&bgc=f0f0f0&wid=566&hei=708&size=536,688",
  },
];
