export const adidasWomenShoes = [
  {
    id: "11",
    title: "ULTRABOOST 1.0 SHOES",
    price: 9500,
    description:
      "From everyday errands to exploring the city, these adidas Ultraboost shoes bring undefeated comfort. The adidas PRIMEKNIT upper is designed to hug your feet for all-day support. ",
    sale: "10%",
    category: "Running",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/1512cb61cfed43f8bc32a148e3adca05_9366/Ultraboost_1.0_Shoes_Pink_ID9664_01_standard.jpg",
  },
  {
    id: "12",
    title: "SUPERNOVA 3 RUNNING SHOES",
    price: 6000,
    description:
      "Whether you run near, far, swift or slow, the adidas Supernova 3 shoes help you run in your comfort zone.",
    sale: "20%",
    category: "Running",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b0934465fe174f34b573ba45101e37cc_9366/Supernova_3_Running_Shoes_White_HQ1805_01_standard.jpg",
  },
  {
    id: "13",
    title: "RUN 60S 3.0 LIFESTYLE RUNNING SHOES",
    price: 3000,
    description:
      "Enjoy those long weekend walks in these adidas trainers. Taking design cues from archival running shoes, they have a clean, versatile aesthetic that stays grounded with an elevated midsole.",
    sale: "30%",
    category: "Running",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/9064bdb0c25b4a75b1ed771e53a49c54_9366/Run_60s_3.0_Lifestyle_Running_Shoes_White_ID1853_01_standard.jpg",
  },
  {
    id: "14",
    title: "CLOUDFOAM PURE SHOES",
    price: 3900,
    description:
      "No one gets it done like you do. Step into a pair of adidas shoes that can keep up. The swift, angular design embodies your on-the-go lifestyle. The Cloudfoam midsole brings ultimate cushioning, so every step feels light and springy. It's a versatile look, with that confident style you're known for.",
    sale: "10%",
    category: "Running",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b9024954fc7c4b7492664e133a9284cb_9366/Cloudfoam_Pure_Shoes_White_IG7376_01_standard.jpg",
  },
  {
    id: "15",
    title: "DURAMO RC SHOES",
    price: 3000,
    description:
      "Run a little faster. Run a little further. With the light, soft and supportive feel of these adidas running shoes, you're set to take the next step in your running journey. ",
    sale: "20%",
    category: "Running",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/c43b629673064f92830dafd3013e8c8e_9366/Duramo_RC_Shoes_Blue_ID2701_01_standard.jpg",
  },
  {
    id: "16",
    title: "DURAMO SPEED SHOES",
    price: 4500,
    description:
      "A combination of a lightweight & breathable engineered mesh upper with a full length LIGHTSTRIKE midsole for faster movement and durable outsole was built for runners looking to learn the ropes and push themselves to the next level.",
    sale: "30%",
    category: "Running",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/2d3755c881f849c0926538a1f54206c9_9366/Duramo_Speed_Shoes_Black_ID9854_01_standard.jpg",
  },
  {
    id: "17",
    title: "DROPSET TRAINER SHOES",
    price: 6500,
    description:
      "Tackle your strength training and gym workouts without hesitation. These adidas training shoes help you level up your game. ",
    sale: "30%",
    category: "Training",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/dc017a7102264fcdb8a7ae6f011e0cdd_9366/Dropset_Trainer_Shoes_Green_GW3900_01_standard.jpg",
  },
  {
    id: "18",
    title: "GAMECOURT 2.0 TENNIS SHOES",
    price: 3500,
    description:
      "Stay confident through every game, set and match. A lightweight mesh upper and padded heel make these adidas Gamecourt 2.0 shoes your perfect tennis partner.",
    sale: "10%",
    category: "Tennis",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b4404527c842424a84b3ae970092eb5e_9366/Gamecourt_2.0_Tennis_Shoes_Turquoise_GW6262_01_standard.jpg",
  },
  {
    id: "19",
    title: "ADIZERO UBERSONIC 4 TENNIS SHOES",
    price: 6800,
    description:
      "Speed buys time. Time earns points. That's why these adidas Adizero Ubersonic 4 tennis shoes were designed to get you to the ball faster.",
    sale: "20%",
    category: "Tennis",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/fe46bc927de24f948bd8af4701505e82_9366/Adizero_Ubersonic_4_Tennis_Shoes_Orange_HQ8392_01_standard.jpg",
  },
  {
    id: "20",
    title: "BARRICADE TENNIS SHOES",
    price: 4900,
    description:
      "The perfect platform for hard court domination. These adidas Barricade tennis shoes have an intuitive lacing system that locks you in by pulling down the neoprene tongue to match your foot shape.",
    sale: "30%",
    category: "Tennis",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/7778b41b65f746dcae6dae9700cb08ce_9366/Barricade_Tennis_Shoes_Orange_GW3816_01_standard.jpg",
  },
];
