export const latestShoes = [
  {
    id: "37",
    title: "FuelCell Trainer v2",
    price: 5499,
    description:
      "Built to perform from the gym floor to the turf to the concrete, the New Balance FuelCell Trainer v2 can do it all. ",
    sale: 10,
    category: "Training",
    promo: "Latest Shoes",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://nb.scene7.com/is/image/NB/mxm100m2_nb_02_i?$pdpflexf2$&qlt=80&fmt=webp&wid=440&hei=440",
  },
  {
    id: "38",
    title: "Minimus TR BOA",
    price: 7499,
    description:
      "Whether you're lifting weights or performing weekly HIIT workouts, our New Balance Minimus TR BOA men's training shoe is a must-have for anyone who craves support and a lightweight feel.",
    sale: 20,
    category: "Training",
    promo: "Latest Shoes",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://nb.scene7.com/is/image/NB/mxmtrbc1_nb_02_i?$pdpflexf2$&qlt=80&fmt=webp&wid=440&hei=440",
  },
  {
    id: "39",
    title: "Coco CG1",
    price: 8499,
    description:
      "A signature shoe is more than a name. Its design expresses the qualities that make an individual stand out from the crowd in their chosen field. That’s why the Coco CG1 is a unique blend of statement making style and high-performance. ",
    sale: 20,
    category: "Basketball",
    promo: "Latest Shoes",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://nb.scene7.com/is/image/NB/uchcocoe_nb_02_i?$pdpflexf2$&qlt=80&fmt=webp&wid=440&hei=440",
  },
  {
    id: "40",
    title: "New Balance 796v3",
    price: 3749,
    description:
      "Enhance your footwork on hard courts with the New Balance 796v3. The 8 mm drop and REVlite cushioning create a reactive feel to help keep you on the ball, while the mesh upper with no-sew construction has a lightweight design to help you feel faster. ",
    sale: 30,
    category: "Basketball",
    promo: "Latest Shoes",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://nb.scene7.com/is/image/NB/mch796e3_nb_02_i?$pdpflexf2$&qlt=80&fmt=webp&wid=440&hei=440",
  },
  {
    id: "41",
    title: "Fresh Foam X 880v13",
    price: 6999,
    description:
      "Function meets performance the New Balance Fresh Foam X 880v13. Featuring a plush and supportive Fresh Foam X midsole and NDurance rubber outsole, this shoe delivers enhanced performance and comfort with each step. ",
    sale: 10,
    category: "Running",
    promo: "Latest Shoes",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://nb.scene7.com/is/image/NB/w880c13_nb_02_i?$pdpflexf2$&qlt=80&fmt=webp&wid=440&hei=440",
  },
  {
    id: "42",
    title: "1540v3",
    price: 8999,
    description:
      "Our 1540v3 is kitted out with technology that helps deliver mile-after-mile stability and combat overpronation. It's made with two layers of performance foam that offers superior support and a soft rebound. ",
    sale: 20,
    category: "Running",
    promo: "Latest Shoes",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://nb.scene7.com/is/image/NB/w1540sp3_nb_02_i?$pdpflexf2$&qlt=80&fmt=webp&wid=440&hei=440",
  },
  {
    id: "43",
    title: "Fresh Foam Roav",
    price: 3749,
    description:
      "Revolutionizing comfort and style, the Fresh Foam Roav women's sneaker delivers an unbeatable ride that is just as comfortable around the foot as it is underneath it.",
    sale: 30,
    category: "Running",
    promo: "Latest Shoes",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://nb.scene7.com/is/image/NB/wroavnv_nb_02_i?$pdpflexf2$&qlt=80&fmt=webp&wid=440&hei=440",
  },
  {
    id: "44",
    title: "Fresh Foam X Hierro v7",
    price: 6999,
    description:
      "For those who take going off the beaten path literally, there’s the Fresh Foam X Hierro, a dedicated, off-road application of our best running technology.",
    sale: 30,
    category: "Running",
    promo: "Latest Shoes",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://nb.scene7.com/is/image/NB/wthiero7_nb_02_i?$pdpflexf2$&qlt=80&fmt=webp&wid=440&hei=440",
  },
  {
    id: "45",
    title: "840v5",
    price: 6999,
    description:
      "Our comfortable and versatile 840v5 women's running shoe is designed for every runner. The full-length ABZORB midsole offers lasting cushioning and a responsive ride no matter your foot type, while the breathable mesh upper provides stretch for a supportive and stable fit where you need it.",
    sale: 30,
    category: "Running",
    promo: "Latest Shoes",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://nb.scene7.com/is/image/NB/w840cm5_nb_02_i?$pdpflexf2$&qlt=80&fmt=webp&wid=440&hei=440",
  },
  {
    id: "46",
    title: "FuelCell 996v5",
    price: 6749,
    description:
      "Zip around the court in comfort and style in the New Balance Fuel Cell 996v5. Our lightweight Fuel Cell foam midsole is paired with a hardwearing NDurance rubber outsole for a tennis shoe that provides superior comfort and traction. ",
    sale: 30,
    category: "Tennis",
    promo: "Latest Shoes",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://nb.scene7.com/is/image/NB/wch996n5_nb_02_i?$pdpflexf2$&qlt=80&fmt=webp&wid=440&hei=440",
  },
  {
    id: "47",
    title: "New Balance 796v3",
    price: 3749,
    description:
      "Enhance your footwork on hard courts with the New Balance 796v3. The 8 mm drop and REVlite cushioning create a reactive feel to help keep you on the ball, while the mesh upper with no-sew construction has a lightweight design to help you feel faster.",
    sale: 10,
    category: "Tennis",
    promo: "Latest Shoes",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://nb.scene7.com/is/image/NB/wch796e3_nb_02_i?$pdpflexf2$&qlt=80&fmt=webp&wid=440&hei=440",
  },
  {
    id: "48",
    title: "DynaSoft Nergize Sport v2",
    price: 3499,
    description:
      "The New Balance DynaSoft Nergize Sport v2 is built to perform and styled for everyday wear. These versatile shoes feature a DynaSoft midsole for plush comfort and adjustable laces for a locked-in and supportive fit.",
    sale: 20,
    category: "Training",
    promo: "Latest Shoes",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://nb.scene7.com/is/image/NB/wnrgsld2_nb_02_i?$pdpflexf2$&qlt=80&fmt=webp&wid=440&hei=440",
  },
  {
    id: "49",
    title: "DynaSoft Nergize Slip On",
    price: 2999,
    description:
      "Slip into the New Balance DynaSoft Nergize Slip On for all-day comfort. These slip-on shoes feature easy on/off construction with a memory insert and DynaSoft midsole foam for cushioned comfort. A rubber outsole provides impressive durability.",
    sale: 10,
    category: "Training",
    promo: "Latest Shoes",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://nb.scene7.com/is/image/NB/wanrgob1_nb_02_i?$pdpflexf2$&qlt=80&fmt=webp&wid=440&hei=440",
  },
  {
    id: "50",
    title: "NB Nergize Sport",
    price: 3249,
    description:
      "Slip on the sleek, sporty comfort of the NB Nergize Sport. These everyday shoes feature REVlite midsole cushioning, a bootie construction for a snug fit, and a durable rubber outsole.",
    sale: 10,
    category: "Training",
    promo: "Latest Shoes",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://nb.scene7.com/is/image/NB/wnrgsbm1_nb_02_i?$pdpflexf2$&qlt=80&fmt=webp&wid=440&hei=440",
  },
  {
    id: "51",
    title: "Nike Invincible 3",
    price: 9895,
    description:
      "With maximum cushioning to support every mile, the Invincible 3 gives you our highest level of comfort underfoot to help you stay on your feet today, tomorrow and beyond.",
    sale: 10,
    category: "Running",
    promo: "Latest Shoes",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/3f4571b9-bbb9-4343-96d3-6467cb217bff/invincible-3-road-running-shoes-Wwmmlp.png",
  },
  {
    id: "52",
    title: "Nike Pegasus Turbo Next Nature SE",
    price: 8395,
    description:
      "Let this esteemed stallion help you log the hard miles. Complete with lighter, responsive foam and a feathery upper, this motley-coloured mare helps you increase tempo without sacrificing comfort as you push towards a personal best.",
    sale: 20,
    category: "Running",
    promo: "Latest Shoes",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/90d94939-2ed4-4b9a-b859-ff41ee6a42c2/pegasus-turbo-next-nature-se-road-running-shoes-tHT957.png",
  },
  {
    id: "53",
    title: "Nike Rival Fly 3",
    price: 4595,
    description:
      "When you're ready to ramp up the speed and go the distance, take off in a model that's built for training and racing.",
    sale: 30,
    category: "Running",
    promo: "Latest Shoes",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/8464ba9d-620f-4094-931a-35d54a2bac1e/rival-fly-3-road-racing-shoes-XbhTCL.png",
  },
  {
    id: "54",
    title: "Jumpman Two Trey",
    price: 8395,
    description:
      "Like Two Trey on MJ's licence plate, let your presence be known. This new generation of Jordan celebrates Mike's time in Chicago, complete with high-quality leather uppers and Air cushioned soles. ",
    sale: 10,
    category: "Basketball",
    promo: "Latest Shoes",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/e64e030d-3fa7-4c29-b03d-4bed1243b807/jumpman-two-trey-shoes-rhmBzG.png",
  },
  {
    id: "55",
    title: "Jordan Max Aura 5",
    price: 7395,
    description:
      "Whenyou need a shoe that's ready 24/7, it's gotta be the Max Aura 5. Inspired by the AJ3, this pair of kicks puts a modern spin on the classic.",
    sale: 20,
    category: "Basketball",
    promo: "Latest Shoes",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/febe38d6-53b5-42fe-abdf-1ec40da5553a/jordan-max-aura-5-shoes-ZBZ4Pz.png",
  },
  {
    id: "56",
    title: "Air Jordan XXXVII Low PF",
    price: 9495,
    description:
      "You've got the hops and the speed—lace up in shoes that enhance what you bring to the court. The latest AJ is all about take-offs and landings, with multiple Air units to get you off the ground.",
    sale: 30,
    category: "Basketball",
    promo: "Latest Shoes",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/1b1055d0-96ee-4ab4-95ba-3c2a3aa1fb1e/air-jordan-xxxvii-low-pf-basketball-shoes-7z7ltC.png",
  },
  {
    id: "57",
    title: "LeBron Witness 7 EP",
    price: 5295,
    description:
      "The longer LeBron's legendary career continues, the more his game needs a design that doesn't weigh him down, yet can still control all that sublime power.",
    sale: 10,
    category: "Basketball",
    promo: "Latest Shoes",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/e740bfd1-caea-422e-b346-92f357f7a446/lebron-witness-7-ep-basketball-shoes-FKPXCg.png",
  },
  {
    id: "58",
    title: "Nike Metcon 8",
    price: 7395,
    description:
      " Our go-to model for training relies on a lighter, more breathable upper than our previous edition to complement our standards of durability and comfort, so that you can float through your cardio, power through your lifts and dominate your workouts.",
    sale: 20,
    category: "Training",
    promo: "Latest Shoes",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/d7a136e4-d9f0-4f84-b090-9587fac2fabc/metcon-8-training-shoes-p9rQzn.png",
  },
  {
    id: "59",
    title: "Nike City Rep TR",
    price: 2895,
    description:
      "The Nike City Rep TR is a versatile shoe that brings durability and flexibility to your active urban lifestyle. ",
    sale: 10,
    category: "Training",
    promo: "Latest Shoes",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/df617f90-6158-4fe4-a5f4-897f3618d9da/city-rep-tr-training-shoes-djC0DF.png",
  },
  {
    id: "60",
    title: "Nike SuperRep Go 3 Next Nature Flyknit",
    price: 5295,
    description:
      "The new Nike SuperRep Go 3 Flyknit Shoe is a radical design story rooted in sustainability and innovation. ",
    sale: 20,
    category: "Training",
    promo: "Latest Shoes",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/4e8664a1-20dc-4a11-a30c-4898390ff7aa/superrep-go-3-next-nature-flyknit-training-shoes-mxKptW.png",
  },
  {
    id: "61",
    title: "Nike Pegasus 40 SE",
    price: 7395,
    description:
      "This version has the same responsiveness and neutral support you love but with improved comfort in those sensitive areas of your foot, like the arch and toes.",
    sale: 10,
    category: "Running",
    promo: "Latest Shoes",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/9ffdabec-87f2-42bf-98b8-ab0a480aace4/pegasus-40-se-road-running-shoes-JM1hs5.png",
  },
  {
    id: "62",
    title: "Nike Pegasus 40 Premium",
    price: 7895,
    description:
      "This version has the same responsiveness and neutral support you love but with improved comfort in those sensitive areas of your foot, like the arch and toes.",
    sale: 10,
    category: "Running",
    promo: "Latest Shoes",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/a02f9a11-2bce-44c4-a85a-86572efedbed/pegasus-40-road-running-shoes-Tp3XzJ.png",
  },
  {
    id: "63",
    title: "Nike React Pegasus Trail 4 SE",
    price: 7395,
    description:
      "Let the Nike React Pegasus Trail 4 take you there and back again with its supportive and springy feel. Underfoot traction keeps you going over rocky terrain, while still providing a smooth ride for the road.",
    sale: 20,
    category: "Running",
    promo: "Latest Shoes",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/8f017a25-9ca1-4f3e-9a66-a8cfe259f497/react-pegasus-trail-4-se-trail-running-shoes-lGbXdr.png",
  },
];
