export const menShoes = [
  {
    id: "1",
    title: "Nike Air Force 1 '07",
    price: "₱6,195",
    description:
      "The radiance lives on with the b-ball original. Crossing hardwood comfort with off-court flair, it puts a fresh spin on what you know best: '80s-inspired construction, bold details and nothin'-but-net style.",
    sale: "",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/e8a96d27-6374-4ec8-81b1-033f476778f1/air-force-1-07-shoes-VWCc04.png",
  },
  {
    id: "2",
    title: "Nike Blazer Low '77 Jumbo",
    price: "₱5,095",
    description: `They say, "Don't fix what works". We say, "Perfect it". The hoops-icon-turned-wardrobe-superstar gets rethought with an oversized Swoosh, thick stitching and jumbo laces. It's classic simplicity meets big and bold—no wonder it's been praised by the streets since '77.`,
    sale: "",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/861b306f-bc46-402a-8b4a-0c1aaa97356c/blazer-low-77-jumbo-shoes-kl0MCq.png",
  },
  {
    id: "3",
    title: "Jordan Series ES",
    price: "₱4,495",
    description: `Inspired by Mike's backyard battles with his older brother Larry, the Jordan Series references their legendary sibling rivalry throughout the design. The rubber sole offers more than just impressive traction—it also tells the story of how MJ came to be #23. Look for the hidden reminder to "Swing for the Fence", a direct quote from Larry to his little bro.`,
    sale: "",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/ba410e57-6124-4805-87ff-6b8020e9f345/jordan-series-es-shoes-FDtg9v.png",
  },
  {
    id: "4",
    title: "Air Jordan 1 Zoom CMFT 2",
    price: "₱8,095",
    description: `Premium suede and Jordan Brand's signature Formula 23 foam come together to give you an extra luxurious (and extra cosy) AJ1. You don't need to play "either or" when it comes to choosing style or comfort with this one—which is nice, 'cause you deserve both.`,
    sale: "",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/eed06a38-dc83-4bd6-a4f3-209d70980736/air-jordan-1-zoom-cmft-2-shoes-nX8Qqx.png",
  },
  {
    id: "5",
    title: "Nike Air Max 270",
    price: "₱7,645",
    description: `Nike's first lifestyle Air Max brings you style, comfort and big attitude in the Nike Air Max 270. The design draws inspiration from Air Max icons, showcasing Nike's greatest innovation with its large window and fresh array of colours.`,
    sale: "",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/oayhdfynrmutq2bcsmpp/air-max-270-shoes-2V5C4p.png",
  },
];
