export const newbalanceMenShoes = [
  {
    id: "31",
    title: "Fresh Foam X 1080v12",
    price: 7999,
    description:
      "The 1080 delivers top-of-the-line performance to every kind of runner, whether you’re training for world-class competition, or catching a rush hour train. The Fresh Foam X 1080v12 represents a consistent progression of the model’s signature qualities.",
    sale: "10%",
    category: "Running",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://nb.scene7.com/is/image/NB/m108012v_nb_02_i?$pdpflexf2$&qlt=80&fmt=webp&wid=440&hei=440",
  },
  {
    id: "32",
    title: "1540v3",
    price: 8999,
    description:
      "Our 1540v3 is kitted out with technology that helps deliver mile-after-mile stability and combat overpronation. It's made with two layers of performance foam that offers superior support and a soft rebound.",
    sale: "20%",
    category: "Running",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://nb.scene7.com/is/image/NB/m1540mb3_nb_02_i?$pdpflexf2$&qlt=80&fmt=webp&wid=440&hei=440",
  },
  {
    id: "33",
    title: "Fresh Foam X 1080 Unlaced",
    price: 3999,
    description:
      "What makes the 1080 unique isn’t just that it’s the best running shoe we make. It delivers the top-of-the-line performance of the best running shoe we make to every kind of runner.",
    sale: "30%",
    category: "Running",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://nb.scene7.com/is/image/NB/m1080scb_nb_02_i?$pdpflexf2$&qlt=80&fmt=webp&wid=440&hei=440",
  },
  {
    id: "34",
    title: "Fresh Foam X Hierro v7",
    price: 6999,
    description:
      "Uneven terrain, debris, and moisture are unique challenges to footwear that require specialized construction. For those who take going off the beaten path literally, there’s the Fresh Foam X Hierro, a dedicated, off-road application of our best running technology.",
    sale: "10%",
    category: "Running",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://nb.scene7.com/is/image/NB/mthieri7_nb_02_i?$pdpflexf2$&qlt=80&fmt=webp&wid=440&hei=440",
  },
  {
    id: "35",
    title: "Fresh Foam Arishi v4 GTX",
    price: 2999,
    description:
      "Hit the road in any weather with the New Balance Fresh Foam Arishi v4 GTX running shoe. Designed to be capable, comfortable and durable, this runner features Fresh Foam midsole cushioning for a plush underfoot feel, and GORE-TEX® waterproof fabric in the upper to help keep feet protected.",
    sale: "20%",
    category: "Running",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://nb.scene7.com/is/image/NB/marisgb4_nb_02_i?$pdpflexf2$&qlt=80&fmt=webp&wid=440&hei=440",
  },
  {
    id: "36",
    title: "Minimus TR",
    price: 5599,
    description:
      "Whether you enjoy lifting weights or performing weekly HIIT workouts, our Minimus TR men's training shoe is a must-have for anyone who craves support and a lightweight feel.",
    sale: "30%",
    category: "Training",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://nb.scene7.com/is/image/NB/mxmtrlk1_nb_02_i?$pdpflexf2$&qlt=80&fmt=webp&wid=440&hei=440",
  },
  {
    id: "37",
    title: "FuelCell Trainer v2",
    price: 5499,
    description:
      "Built to perform from the gym floor to the turf to the concrete, the New Balance FuelCell Trainer v2 can do it all. ",
    sale: "10%",
    category: "Training",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://nb.scene7.com/is/image/NB/mxm100m2_nb_02_i?$pdpflexf2$&qlt=80&fmt=webp&wid=440&hei=440",
  },
  {
    id: "38",
    title: "Minimus TR BOA",
    price: 7499,
    description:
      "Whether you're lifting weights or performing weekly HIIT workouts, our New Balance Minimus TR BOA men's training shoe is a must-have for anyone who craves support and a lightweight feel.",
    sale: "20%",
    category: "Training",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://nb.scene7.com/is/image/NB/mxmtrbc1_nb_02_i?$pdpflexf2$&qlt=80&fmt=webp&wid=440&hei=440",
  },
  {
    id: "39",
    title: "Coco CG1",
    price: 8499,
    description:
      "A signature shoe is more than a name. Its design expresses the qualities that make an individual stand out from the crowd in their chosen field. That’s why the Coco CG1 is a unique blend of statement making style and high-performance. ",
    sale: "20%",
    category: "Basketball",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://nb.scene7.com/is/image/NB/uchcocoe_nb_02_i?$pdpflexf2$&qlt=80&fmt=webp&wid=440&hei=440",
  },
  {
    id: "40",
    title: "New Balance 796v3",
    price: 3749,
    description:
      "Enhance your footwork on hard courts with the New Balance 796v3. The 8 mm drop and REVlite cushioning create a reactive feel to help keep you on the ball, while the mesh upper with no-sew construction has a lightweight design to help you feel faster. ",
    sale: "30%",
    category: "Basketball",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://nb.scene7.com/is/image/NB/mch796e3_nb_02_i?$pdpflexf2$&qlt=80&fmt=webp&wid=440&hei=440",
  },
];
