export const nikeMenShoes = [
  {
    id: "51",
    title: "Nike Invincible 3",
    price: 9895,
    description:
      "With maximum cushioning to support every mile, the Invincible 3 gives you our highest level of comfort underfoot to help you stay on your feet today, tomorrow and beyond.",
    sale: 10,
    category: "Running",
    promo: "New Arrival",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/3f4571b9-bbb9-4343-96d3-6467cb217bff/invincible-3-road-running-shoes-Wwmmlp.png",
  },
  {
    id: "52",
    title: "Nike Pegasus Turbo Next Nature SE",
    price: 8395,
    description:
      "Let this esteemed stallion help you log the hard miles. Complete with lighter, responsive foam and a feathery upper, this motley-coloured mare helps you increase tempo without sacrificing comfort as you push towards a personal best.",
    sale: 20,
    category: "Running",
    promo: "New Arrival",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/90d94939-2ed4-4b9a-b859-ff41ee6a42c2/pegasus-turbo-next-nature-se-road-running-shoes-tHT957.png",
  },
  {
    id: "53",
    title: "Nike Rival Fly 3",
    price: 4595,
    description:
      "When you're ready to ramp up the speed and go the distance, take off in a model that's built for training and racing.",
    sale: 30,
    category: "Running",
    promo: "New Arrival",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/8464ba9d-620f-4094-931a-35d54a2bac1e/rival-fly-3-road-racing-shoes-XbhTCL.png",
  },
  {
    id: "54",
    title: "Jumpman Two Trey",
    price: 8395,
    description:
      "Like Two Trey on MJ's licence plate, let your presence be known. This new generation of Jordan celebrates Mike's time in Chicago, complete with high-quality leather uppers and Air cushioned soles. ",
    sale: 10,
    category: "Basketball",
    promo: "New Arrival",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/e64e030d-3fa7-4c29-b03d-4bed1243b807/jumpman-two-trey-shoes-rhmBzG.png",
  },
  {
    id: "55",
    title: "Jordan Max Aura 5",
    price: 7395,
    description:
      "Whenyou need a shoe that's ready 24/7, it's gotta be the Max Aura 5. Inspired by the AJ3, this pair of kicks puts a modern spin on the classic.",
    sale: 20,
    category: "Basketball",
    promo: "New Arrival",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/febe38d6-53b5-42fe-abdf-1ec40da5553a/jordan-max-aura-5-shoes-ZBZ4Pz.png",
  },
  {
    id: "56",
    title: "Air Jordan XXXVII Low PF",
    price: 9495,
    description:
      "You've got the hops and the speed—lace up in shoes that enhance what you bring to the court. The latest AJ is all about take-offs and landings, with multiple Air units to get you off the ground.",
    sale: 30,
    category: "Basketball",
    promo: "New Arrival",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/1b1055d0-96ee-4ab4-95ba-3c2a3aa1fb1e/air-jordan-xxxvii-low-pf-basketball-shoes-7z7ltC.png",
  },
  {
    id: "57",
    title: "LeBron Witness 7 EP",
    price: 5295,
    description:
      "The longer LeBron's legendary career continues, the more his game needs a design that doesn't weigh him down, yet can still control all that sublime power.",
    sale: 10,
    category: "Basketball",
    promo: "New Arrival",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/e740bfd1-caea-422e-b346-92f357f7a446/lebron-witness-7-ep-basketball-shoes-FKPXCg.png",
  },
  {
    id: "58",
    title: "Nike Metcon 8",
    price: 7395,
    description:
      " Our go-to model for training relies on a lighter, more breathable upper than our previous edition to complement our standards of durability and comfort, so that you can float through your cardio, power through your lifts and dominate your workouts.",
    sale: 20,
    category: "Training",
    promo: "New Arrival",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/d7a136e4-d9f0-4f84-b090-9587fac2fabc/metcon-8-training-shoes-p9rQzn.png",
  },
  {
    id: "59",
    title: "Nike City Rep TR",
    price: 2895,
    description:
      "The Nike City Rep TR is a versatile shoe that brings durability and flexibility to your active urban lifestyle. ",
    sale: 10,
    category: "Training",
    promo: "New Arrival",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/df617f90-6158-4fe4-a5f4-897f3618d9da/city-rep-tr-training-shoes-djC0DF.png",
  },
  {
    id: "60",
    title: "Nike SuperRep Go 3 Next Nature Flyknit",
    price: 5295,
    description:
      "The new Nike SuperRep Go 3 Flyknit Shoe is a radical design story rooted in sustainability and innovation. ",
    sale: 20,
    category: "Training",
    promo: "New Arrival",
    for: "Men's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/4e8664a1-20dc-4a11-a30c-4898390ff7aa/superrep-go-3-next-nature-flyknit-training-shoes-mxKptW.png",
  },
];
