export const nikeWomenShoes = [
  {
    id: "61",
    title: "Nike Pegasus 40 SE",
    price: 7395,
    description:
      "This version has the same responsiveness and neutral support you love but with improved comfort in those sensitive areas of your foot, like the arch and toes.",
    sale: 10,
    category: "Running",
    promo: "",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/9ffdabec-87f2-42bf-98b8-ab0a480aace4/pegasus-40-se-road-running-shoes-JM1hs5.png",
  },
  {
    id: "62",
    title: "Nike Pegasus 40 Premium",
    price: 7895,
    description:
      "This version has the same responsiveness and neutral support you love but with improved comfort in those sensitive areas of your foot, like the arch and toes.",
    sale: 10,
    category: "Running",
    promo: "",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/a02f9a11-2bce-44c4-a85a-86572efedbed/pegasus-40-road-running-shoes-Tp3XzJ.png",
  },
  {
    id: "63",
    title: "Nike React Pegasus Trail 4 SE",
    price: 7395,
    description:
      "Let the Nike React Pegasus Trail 4 take you there and back again with its supportive and springy feel. Underfoot traction keeps you going over rocky terrain, while still providing a smooth ride for the road.",
    sale: 20,
    category: "Running",
    promo: "",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/8f017a25-9ca1-4f3e-9a66-a8cfe259f497/react-pegasus-trail-4-se-trail-running-shoes-lGbXdr.png",
  },
  {
    id: "64",
    title: "Nike SuperRep Go 3 Flyknit Next Nature",
    price: 5295,
    description:
      "The new Nike SuperRep Go 3 Flyknit is a radical design story rooted in innovation. Made from at least 20% recycled content by weight, the zoned Flyknit construction wraps your foot in 360 degrees of comfort and support.",
    sale: 30,
    category: "Training",
    promo: "",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/00cd41dc-cff3-4cf5-a47c-37fb3ae02698/superrep-go-3-flyknit-next-nature-training-shoes-zKqgRc.png",
  },
  {
    id: "65",
    title: "Nike City Rep TR",
    price: 2895,
    description:
      "The Nike City Rep TR is a versatile shoe that brings durability and flexibility to your active lifestyle.",
    sale: 30,
    category: "Training",
    promo: "",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/8e714e1e-ecc0-430c-9a57-0ef48d1710a9/city-rep-tr-training-shoes-k6VCMk.png",
  },
  {
    id: "66",
    title: "Nike Zoom Bella 6",
    price: 4695,
    description:
      "Unleash your innermost strength and spirit in the Nike Zoom Bella 6. This design supports heavy lifts, explosive movements and primal post-set struts as you flaunt your hard-earned progress on the gym floor.",
    sale: 10,
    category: "Training",
    promo: "",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/d638751c-f0df-49bc-ba7f-3a8229fc3416/zoom-bella-6-training-shoes-PX75xS.png",
  },
  {
    id: "67",
    title: "Nike Free Metcon 4",
    price: 3869,
    description:
      "The Nike Free Metcon 4 combines flexibility with stability to help you get the most out of your training programme. ",
    sale: 10,
    category: "Training",
    promo: "",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/d8b946dc-2f54-4c8c-bb79-36cdbcad876c/free-metcon-4-training-shoes-k5B8Jf.png",
  },
  {
    id: "68",
    title: "Air Jordan XXXVII Low",
    price: 10839,
    description:
      "A basketball shoe for you and your unique game. We gathered insights from female ballers and integrated them into this edition of the AJ XXXVII Low, engineered specifically for women.",
    sale: 20,
    category: "Basketball",
    promo: "",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/421da929-53d5-44fe-a658-6635acec612a/air-jordan-xxxvii-low-basketball-shoes-Z2glMj.png",
  },
  {
    id: "69",
    title: "Air Jordan 1 Elevate High",
    price: 8595,
    description:
      "Classic Jordan style reaches new heights in this lifted AJ-1. The platform stance and high-top collar make a statement, while crisp leather and flashy finishes make these kicks the winning assist your outfit needs.",
    sale: 30,
    category: "Basketball",
    promo: "",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/bac26860-b8ac-4dfa-92c0-00ebc8416e2b/air-jordan-1-elevate-high-shoes-rKPNHR.png",
  },
  {
    id: "70",
    title: "Air Jordan 1 Mid SE",
    price: 4439,
    description:
      "These AJ1s give a classic silhouette the royal treatment. An all-over velvet upper in Purple Smoke looks super luxe, while the embroidered Swoosh, plush laces and colour-matched outsole let you hit refresh on a beloved hoops design.",
    sale: 10,
    category: "Basketball",
    promo: "",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/ac05bee4-331c-43b0-bf9d-8396f3ba4983/air-jordan-1-mid-se-shoes-56JJcP.png",
  },
];
