export const underArmourWomenShoes = [
  {
    id: "81",
    title: "UA Charged Bandit Trail 2",
    price: 3357,
    description:
      "Specially built for trail running, with crazy cushioning, traction that grips even muddy terrain, and the extra protection trail runners need to keep going.",
    sale: 10,
    category: "Running",
    promo: "Trending",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://underarmour.scene7.com/is/image/Underarmour/3024191-500_DEFAULT?rp=standard-30pad|pdpZoomDesktop&scl=0.50&fmt=jpg&qlt=85&resMode=sharp2&cache=on,on&bgc=f0f0f0&wid=1836&hei=1950&size=850,850",
  },
  {
    id: "82",
    title: "UA HOVR™ Sonic 5",
    price: 4197,
    description:
      "The UA HOVR™ Sonic is a no-brainer for runners who like distance but want more flexibility, a breathable feel, and the real-time feedback of Form Coaching from UA MapMyRun™ to help you run better every time you lace them up.",
    sale: 20,
    category: "Running",
    promo: "Trending",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://underarmour.scene7.com/is/image/Underarmour/3024906-001_DEFAULT?rp=standard-30pad|pdpMainDesktop&scl=1&fmt=jpg&qlt=85&resMode=sharp2&cache=on,on&bgc=f0f0f0&wid=566&hei=708&size=536,688",
  },
  {
    id: "83",
    title: "UA HOVR™ Phantom 3",
    price: 5397,
    description:
      "The off-season is for getting better. That means lots of running. Fast, stretchy UA HOVR™ Phantom 3 helps you explode through interval after interval with even more energy-returning UA HOVR™ cushioning. Run now…win later.",
    sale: 30,
    category: "Running",
    promo: "Trending",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://underarmour.scene7.com/is/image/Underarmour/3025517-602_DEFAULT?rp=standard-30pad|pdpZoomDesktop&scl=0.50&fmt=jpg&qlt=85&resMode=sharp2&cache=on,on&bgc=f0f0f0&wid=1836&hei=1950&size=850,850",
  },
  {
    id: "84",
    title: " UA HOVR™ Phantom 3 Slip Pride ",
    price: 8595,
    description:
      "This year's UA Pride collection supports Unmatched Athlete, WorldPride, and Rainbow Labs, each with the goal of providing safe places for LGBTQ+ athletes and allies to play and compete.",
    sale: 10,
    category: "Running",
    promo: "Trending",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://underarmour.scene7.com/is/image/Underarmour/3026350-100_DEFAULT?rp=standard-30pad|pdpMainDesktop&scl=1&fmt=jpg&qlt=85&resMode=sharp2&cache=on,on&bgc=f0f0f0&wid=566&hei=708&size=536,688",
  },
  {
    id: "85",
    title: "UA Charged Intake 5",
    price: 3357,
    description:
      "UA Charged Intake was designed to keep your feet cooler and drier, so you can log as many miles as you want.",
    sale: 10,
    category: "Running",
    promo: "Trending",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://underarmour.scene7.com/is/image/Underarmour/3023564-600_DEFAULT?rp=standard-30pad|pdpMainDesktop&scl=1&fmt=jpg&qlt=85&resMode=sharp2&cache=on,on&bgc=f0f0f0&wid=566&hei=708&size=536,688",
  },
  {
    id: "86",
    title: "UA HOVR™ Omnia Metallic",
    price: 3777,
    description:
      "Feels like a cloud and fits like a glove. We took our super-springy UA HOVR™ cushioning and put it in a trainer that's built specifically for the female foot.",
    sale: 10,
    category: "Training",
    promo: "Trending",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://underarmour.scene7.com/is/image/Underarmour/3025567-001_DEFAULT?rp=standard-30pad|pdpMainDesktop&scl=1&fmt=jpg&qlt=85&resMode=sharp2&cache=on,on&bgc=f0f0f0&wid=566&hei=708&size=536,688",
  },
  {
    id: "87",
    title: " UA SlipSpeed™ ",
    price: 8595,
    description:
      "These are the most versatile training shoes we've ever made. They feel great, feel cool, cushion better, fit perfectly, handle your toughest training, AND have a heel that converts easily from recover mode to train mode.",
    sale: 30,
    category: "Training",
    promo: "Trending",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://underarmour.scene7.com/is/image/Underarmour/3027057-300_DEFAULT?rp=standard-30pad|pdpMainDesktop&scl=1&fmt=jpg&qlt=85&resMode=sharp2&cache=on,on&bgc=f0f0f0&wid=566&hei=708&size=536,688",
  },
  {
    id: "88",
    title: "UA TriBase™ Reign 4 ",
    price: 8595,
    description:
      "If you're a serious lifter these are the shoes you need. The midfoot strap keeps you locked in, the TPU heel lift helps support hip and ankle flexibility, and the outsole is firm and flat for maximum ground contact.",
    sale: 30,
    category: "Training",
    promo: "Trending",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://underarmour.scene7.com/is/image/Underarmour/3025053-500_DEFAULT?rp=standard-30pad|pdpZoomDesktop&scl=0.50&fmt=jpg&qlt=85&resMode=sharp2&cache=on,on&bgc=f0f0f0&wid=1836&hei=1950&size=850,850",
  },
  {
    id: "89",
    title: "UA Flow Breakthru 3 LE",
    price: 6795,
    description:
      "Women's feet are a different shape than men's. That's a fact. These shoes were built for women by women, giving you the best fit, support, and flex. And, with UA Flow cushioning you also get the best grip on any court.",
    sale: 10,
    category: "Basketball",
    promo: "Trending",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://underarmour.scene7.com/is/image/Underarmour/3026761-100_DEFAULT?rp=standard-30pad|pdpMainDesktop&scl=1&fmt=jpg&qlt=85&resMode=sharp2&cache=on,on&bgc=f0f0f0&wid=566&hei=708&size=536,688",
  },
  {
    id: "90",
    title: "Curry 1 Low FloTro",
    price: 3456,
    description:
      "These shoes combine the light, grippy speed of Curry 10's UA Flow cushioning with the custom feel of your favorite Curry 1's form-fitting upper. Why? Because this unreal combo puts you a step ahead all game long.",
    sale: 20,
    category: "Basketball",
    promo: "Trending",
    for: "Women's Shoes",
    size: [
      "US 6.5",
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 12.5",
      "US 13",
    ],
    image:
      "https://underarmour.scene7.com/is/image/Underarmour/3026278-401_DEFAULT?rp=standard-30pad|pdpMainDesktop&scl=1&fmt=jpg&qlt=85&resMode=sharp2&cache=on,on&bgc=f0f0f0&wid=566&hei=708&size=536,688",
  },
];
